/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.obi.services.Form;

import java.sql.DatabaseMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.obi.services.util.Ico;

/**
 *
 * @author r.hendrick
 */
public class DatabaseInformationsFrame extends javax.swing.JDialog {

    /**
     * Creates new form DatabaseInformations
     */
    public DatabaseInformationsFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    
    public void doUpdateWithDatabaseMetaData(DatabaseMetaData dm){
        try {
            labelDriverName.setText(dm.getDriverName());
            labelDriverVersion.setText(dm.getDriverVersion());
            labelProductName.setText(dm.getDatabaseProductName());
            labelProductVersion.setText(dm.getDatabaseProductVersion());
        } catch (SQLException ex) {
            Logger.getLogger(DatabaseInformationsFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelForDriverName = new javax.swing.JLabel();
        labelForDriverVersion = new javax.swing.JLabel();
        labelForProductName = new javax.swing.JLabel();
        labelForProductVersion = new javax.swing.JLabel();
        labelDriverName = new javax.swing.JLabel();
        labelDriverVersion = new javax.swing.JLabel();
        labelProductName = new javax.swing.JLabel();
        labelProductVersion = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Information base de donnée");
        setIconImage(Ico.i16("/img/obi/obi-signet-light.png", this).getImage());

        labelForDriverName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelForDriverName.setLabelFor(labelDriverName);
        labelForDriverName.setText("Driver Nom");

        labelForDriverVersion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelForDriverVersion.setLabelFor(labelDriverVersion);
        labelForDriverVersion.setText("Driver Version");

        labelForProductName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelForProductName.setLabelFor(labelProductName);
        labelForProductName.setText("Produit Nom");

        labelForProductVersion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelForProductVersion.setLabelFor(labelProductVersion);
        labelForProductVersion.setText("Produit Version");

        labelDriverName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelDriverName.setText("-");

        labelDriverVersion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelDriverVersion.setText("-");

        labelProductName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelProductName.setText("-");

        labelProductVersion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelProductVersion.setText("-");

        btnClose.setText("Fermer");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelForDriverName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelForDriverVersion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelForProductName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelForProductVersion, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(labelProductVersion, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(labelProductName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(labelDriverVersion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(labelDriverName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelForDriverName)
                    .addComponent(labelDriverName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelForDriverVersion)
                    .addComponent(labelDriverVersion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelForProductName)
                    .addComponent(labelProductName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelForProductVersion)
                    .addComponent(labelProductVersion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelDriverName;
    private javax.swing.JLabel labelDriverVersion;
    private javax.swing.JLabel labelForDriverName;
    private javax.swing.JLabel labelForDriverVersion;
    private javax.swing.JLabel labelForProductName;
    private javax.swing.JLabel labelForProductVersion;
    private javax.swing.JLabel labelProductName;
    private javax.swing.JLabel labelProductVersion;
    // End of variables declaration//GEN-END:variables
}
